export default () => [
    'If you could see a live performance from any singer, alive or dead, who would you choose? Where would the performance take place?',
    'If you had to be quarantined in one place for a month, what would you want that place to look like? Who would be quarantined with you? What entertainment resources would you want?',
    'You just won the lottery. What is the first thing you’re going to do?',
    'If you could have any animal, real or mythological, as a pet, which would you choose?',
    'Pick one of your favorite fairy tales or classic stories. Rewrite a scene from the perspective of a side character. What are some details that the main characters might not have noticed?',
    'If you were famous, what would you like to be known for? How would you help make the world a better place?',
    'If you could travel to any fictional world, where would you go? What characters would you want to meet? Would you choose to alter their story?',
    'Pick a color. Try to describe that color without mentioning its name. What emotions are tied to the color? What memories do you have of it? What sets it apart from others?',
    'If you could invent an ice cream flavor, what would it taste like? What would you name it?',
    'If you could travel to any point in the past, where would you go? Who would you meet? How would you avoid making dramatic changes?',
    'If you could change a part of your environment (your house, furniture, yard, etc), what would you change? How much time would it take? Is there a way you can make a small change for the better?',
    'What is one thing you’ve been putting off? Write about how you would feel if you got it done? How could you reward yourself after?',
    'Make a list of your friends, family, coworkers, pets, etc. Write down the things you like about each person. What makes them special? Do the same for yourself.',
    'Write about one of your fondest memories. Put extra attention into how you felt in that moment. What are some things you could do to keep making positive memories?',
    'Make a list of your achievements. What makes you proud? What are some little things that you have done in the past few days that have helped make your life easier?',
    'What is your favorite movie? Write about one of the struggles the characters faced. How did they overcome it?',
    'Pick a fictional character that you admire. Make a list of their positive qualities. Then, make a list of their flaws. What makes them human? What do you have in common?',
    'Make a list of songs that you like to listen to when you’re sad. What do you listen to when you’re happy? What songs help you cope with strong emotions?',
    'Write about a person who has made a positive impact on your life. What did they do that helped you the most? What would you say to them if you could talk to them now? How can you help someone else with similar struggles?',
    'Write about a book that you would happily read again. How has this book brought comfort in times of hopelessness? Who would you recommend this book to?',
    'Write a letter to your future self. Write about the things you hope for. Ask yourself questions. Even if you don’t get the answers right away, you can keep looking for them. Then, try writing one to your past self.',
    'Write about your clothes. How do they smell? How do they feel? Include the things you like about them. How do you feel when you’re wearing them?',
    'In times of stress, take a few moments to write about things that make you happy. What are you grateful for?',
    'Write about a time you faced a challenge and overcame it. How did you feel afterward? Was it as bad as you’d thought?',
    'Make a list of people you can reach out to when you feel anxious. Do you have a way to contact them? How would they help you?',
    'Write about the way you see yourself in social situations. What are some of the things you do that make you insecure? If someone else did/said the same thing, would you judge them?',
    'Write about advice that you would give to a friend who is stressed. What would you tell them to try? What are things that have helped you in the past?',
    'Make a list of things you like about yourself, things you want to do someday, and reasons to keep trying new things.',
    'If you could do anything without failing, what would you try? What is standing in your way now?',
    'Write about your ideal day. What would you do? Where would you go? Who would you spend the day with?',
    'Make a list of places to go during the next month. They can be specific stores, restaurants, or nearby cities. What would you do at each place?'
]